#!/usr/bin/env escript
%% -*- erlang -*-
%% Copyright (c) 2012-2022 Peter Morgan <peter.james.morgan@gmail.com>
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%% http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.
%%

main([]) ->
    debug(os:env()),
    set_output("script_name", escript:script_name()),
    set_output(
      "time",
      calendar:system_time_to_rfc3339(erlang:system_time(second))),
    io:format("Hello ~s~n", [WhoToGreet]).

set_output(Name, Value) ->
    io:format("::set-output name=~s::~s~n", [Name, Value]).

get_input(Name) ->
    case os:getenv("INPUT_" ++ string:uppercase(Name)) of
        false ->
            error(badarg, [Name]);

        Value ->
            Value
    end.

debug(Message) ->
    io:format("::debug::~p~n", [Message]).
